// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bookshelf.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	bookshelf.proto

It has these top-level messages:
	LookupRequest
	BookRecord
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BookCategory int32

const (
	BookCategory_MAGAZINE BookCategory = 0
	BookCategory_CARTOON  BookCategory = 1
)

var BookCategory_name = map[int32]string{
	0: "MAGAZINE",
	1: "CARTOON",
}
var BookCategory_value = map[string]int32{
	"MAGAZINE": 0,
	"CARTOON":  1,
}

func (x BookCategory) String() string {
	return proto.EnumName(BookCategory_name, int32(x))
}
func (BookCategory) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type LookupRequest struct {
	Title string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
}

func (m *LookupRequest) Reset()                    { *m = LookupRequest{} }
func (m *LookupRequest) String() string            { return proto.CompactTextString(m) }
func (*LookupRequest) ProtoMessage()               {}
func (*LookupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LookupRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type BookRecord struct {
	Title            string       `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Auther           string       `protobuf:"bytes,2,opt,name=auther" json:"auther,omitempty"`
	PublicatioinDate string       `protobuf:"bytes,3,opt,name=publicatioin_date,json=publicatioinDate" json:"publicatioin_date,omitempty"`
	Category         BookCategory `protobuf:"varint,4,opt,name=category,enum=pb.BookCategory" json:"category,omitempty"`
}

func (m *BookRecord) Reset()                    { *m = BookRecord{} }
func (m *BookRecord) String() string            { return proto.CompactTextString(m) }
func (*BookRecord) ProtoMessage()               {}
func (*BookRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BookRecord) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *BookRecord) GetAuther() string {
	if m != nil {
		return m.Auther
	}
	return ""
}

func (m *BookRecord) GetPublicatioinDate() string {
	if m != nil {
		return m.PublicatioinDate
	}
	return ""
}

func (m *BookRecord) GetCategory() BookCategory {
	if m != nil {
		return m.Category
	}
	return BookCategory_MAGAZINE
}

func init() {
	proto.RegisterType((*LookupRequest)(nil), "pb.LookupRequest")
	proto.RegisterType((*BookRecord)(nil), "pb.BookRecord")
	proto.RegisterEnum("pb.BookCategory", BookCategory_name, BookCategory_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Bookshelf service

type BookshelfClient interface {
	Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*BookRecord, error)
}

type bookshelfClient struct {
	cc *grpc.ClientConn
}

func NewBookshelfClient(cc *grpc.ClientConn) BookshelfClient {
	return &bookshelfClient{cc}
}

func (c *bookshelfClient) Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*BookRecord, error) {
	out := new(BookRecord)
	err := grpc.Invoke(ctx, "/pb.Bookshelf/Lookup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Bookshelf service

type BookshelfServer interface {
	Lookup(context.Context, *LookupRequest) (*BookRecord, error)
}

func RegisterBookshelfServer(s *grpc.Server, srv BookshelfServer) {
	s.RegisterService(&_Bookshelf_serviceDesc, srv)
}

func _Bookshelf_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookshelfServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Bookshelf/Lookup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookshelfServer).Lookup(ctx, req.(*LookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bookshelf_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Bookshelf",
	HandlerType: (*BookshelfServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lookup",
			Handler:    _Bookshelf_Lookup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bookshelf.proto",
}

func init() { proto.RegisterFile("bookshelf.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xca, 0xcf, 0xcf,
	0x2e, 0xce, 0x48, 0xcd, 0x49, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52,
	0x52, 0xe5, 0xe2, 0xf5, 0xc9, 0xcf, 0xcf, 0x2e, 0x2d, 0x08, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e,
	0x11, 0x12, 0xe1, 0x62, 0x2d, 0xc9, 0x2c, 0xc9, 0x49, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x82, 0x70, 0x94, 0xa6, 0x32, 0x72, 0x71, 0x39, 0xe5, 0xe7, 0x67, 0x07, 0xa5, 0x26, 0xe7, 0x17,
	0xa5, 0x60, 0x57, 0x24, 0x24, 0xc6, 0xc5, 0x96, 0x58, 0x5a, 0x92, 0x91, 0x5a, 0x24, 0xc1, 0x04,
	0x16, 0x86, 0xf2, 0x84, 0xb4, 0xb9, 0x04, 0x0b, 0x4a, 0x93, 0x72, 0x32, 0x93, 0x13, 0x4b, 0x32,
	0xf3, 0x33, 0xf3, 0xe2, 0x53, 0x12, 0x4b, 0x52, 0x25, 0x98, 0xc1, 0x4a, 0x04, 0x90, 0x25, 0x5c,
	0x12, 0x4b, 0x52, 0x85, 0x74, 0xb8, 0x38, 0x92, 0x13, 0x4b, 0x52, 0xd3, 0xf3, 0x8b, 0x2a, 0x25,
	0x58, 0x14, 0x18, 0x35, 0xf8, 0x8c, 0x04, 0xf4, 0x0a, 0x92, 0xf4, 0x40, 0x96, 0x3b, 0x43, 0xc5,
	0x83, 0xe0, 0x2a, 0xb4, 0x34, 0xb9, 0x78, 0x90, 0x65, 0x84, 0x78, 0xb8, 0x38, 0x7c, 0x1d, 0xdd,
	0x1d, 0xa3, 0x3c, 0xfd, 0x5c, 0x05, 0x18, 0x84, 0xb8, 0xb9, 0xd8, 0x9d, 0x1d, 0x83, 0x42, 0xfc,
	0xfd, 0xfd, 0x04, 0x18, 0x8d, 0xac, 0xb8, 0x38, 0x9d, 0x60, 0x01, 0x20, 0xa4, 0xcb, 0xc5, 0x06,
	0xf1, 0xb6, 0x90, 0x20, 0xc8, 0x74, 0x94, 0x20, 0x90, 0xe2, 0x83, 0x59, 0x08, 0xf1, 0xad, 0x12,
	0x43, 0x12, 0x1b, 0x38, 0xc0, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x14, 0x01, 0x5d, 0xa4,
	0x43, 0x01, 0x00, 0x00,
}
